swagger: '2.0'
info:
  title: Booking Guru API
  version: v1
  description: |
    Welcome to the Booking Guru API, we're glad you could make it. Let's poke around a bit.

    And just in case you have no idea where you are, [Booking Guru](http://bookingsoftware.guru)
    is a software package for spiritual retreat centers to manage programs, registrations, finances
    and everything in between.

    ## Security token

    The first thing you'll need is the security token for your installation. Go to the Reg. Settings
    on your install, select the API tab and grab the token that appears there.

    ![](resource/token.png "Where is my token?")

    If there isn't a token there yet, hit *Generate Token*, then *Save changes* and then copy the token.

    Set a couple of environment variables so it's easier to run the samples:

    ```
    $ export BGDOMAIN=<domain>
    $ export BGTOKEN=<token>
    ```

    The `<domain>` is your install's domain, and `<token>` is the token you just got from the admin UI.

    Lets take a look at some data.

    ## Curl examples

    Get latest 20 programs:

    ```
    $ curl "https://$BGDOMAIN/api/v1/programs?token=$BGTOKEN"
    ```

    Get latest 20 registrations:

    ```
    $ curl "https://$BGDOMAIN/api/v1/registrations?token=$BGTOKEN"
    ```

    Get all registrations (*dont' do this too often if you have a large install*):

    ```
    $ curl "https://$BGDOMAIN/api/v1/registrations?token=$BGTOKEN&limit=0"
    ```

    Get all registrations for a particular program:

    ```
    $ curl "https://$BGDOMAIN/api/v1/registrations?token=$BGTOKEN&program_slug=3-day-escape"
    ```

    ## Examples

    We're working on some deeper examples in PHP, Python and Javascript that we'll push to this repo real soon.

    ## API Reference

    Following is the reference for the requests you can currently do against the API.

    *Notes:*

    1. All values with the `date` type are in `YYYY-MM-DD` format, all values with the `date-time` type are in the `YYYY-MM-DDTHH:MM:SS` format.

    2. If a parameters can take multiple values (the `id` parameter usually does) provide multiple values separated by commas without spaces.

# -------------------------------------------------------------------------------------------------

basePath: /api/v1
schemes: [https]
produces: [application/json]
  
paths:
  /programs:
    get:
      summary: Get program info
      description: |
        Retrieves information about programs, their dates and and categories.

      parameters:
        - name: token
          in: query
          type: string
          description: Security token
          required: true

        - name: limit
          in: query
          type: integer
          description: |
            Limit number of return values. The default limit is 20. Pass `limit=0` To get all the objects without
            limits, but please use this with caution to not overload our servers.

        - name: id
          in: query
          type: array
          items:
            type: integer
          description: |
            Gets programs with a specific id or list of ids. To get multiple objects, provide a comma separated list of values.

      responses:
        200:
          description:
            An array of programs
          schema:
            type: array
            items:
              $ref: '#/definitions/Program'
        400:
          description: An error
          schema:
            $ref: '#/definitions/Error'

  /registrations:
    get:
      summary: Get registration info
      description: |
        Retrieves registration details including names, emails and programs people have registered to. Registrations are always sorted 
        in reverse chronological order with the newest registrations at the top or the result list.

      parameters:
        - name: token
          in: query
          type: string
          description: Security token
          required: true

        - name: limit
          in: query
          type: integer
          description: |
            Limit number of return values. The default limit is 20. Pass `limit=0` To get all the objects without
            limits, but please use this with caution to not overload our servers.

        - name: id
          in: query
          type: array
          items:
            type: integer
          description: |
            Gets registrations with a specific id or list of ids.

        - name: program_id
          in: query
          type: integer
          description: |
            Gets all the registrations for a specific program.

        - name: min_date
          in: query
          type: string
          format: date
          description: |
            Gets registrations that were submitted on or after `min_date`. Can be combined with `max_date` for a range of dates.

        - name: max_date
          in: query
          type: string
          format: date
          description: |
            Gets registrations that were submitted on or before `max_date`.

        - name: min_stay
          in: query
          type: string
          format: date
          description: |
            Gets all registrations for which the registration stay dates are on or after `min_stay`. In particular
            this includes registrations that start on `min_stay`, those that start before `min_stay` and end on or after it,
            and those that start after `min_stay`. This will not include registrations that end before `min_stay`.

        - name: max_stay
          in: query
          type: string
          format: date
          description: |
            Gets all registrations for which the registration stay dates are on or before `max_stay`. In particular
            this includes registrations that those that start before `max_stay` and end on or after it,
            and those that start after `max_stay`. This will not include registrations that start after `max_stay`.

      responses:
        200:
          description:
            An array of registrations
          schema:
            type: array
            items:
              $ref: '#/definitions/Registration'
        400:
          description: An error
          schema:
            $ref: '#/definitions/Error'

  /transactions:
    get:
      summary: Get transaction info
      description: |
        Transactions represent the financial details of the registration, including items the guest has purchased, discounts, taxes,
        credit card payments, cash payments and any other custom transaction type you may have defined on your install.

        Transactions are always sorted in reverse chronological order with the newest transaction at the top or the result list.

      parameters:
        - name: token
          in: query
          type: string
          description: Security token
          required: true

        - name: limit
          in: query
          type: integer
          description: |
            Limit number of return values. The default limit is 20. Pass `limit=0` To get all the objects without
            limits, but please use this with caution to not overload our servers.

        - name: id
          in: query
          type: array
          items:
            type: integer
          description: |
            Filter transactions with a specific id or list of ids.

        - name: class
          in: query
          type: array
          items:
            type: string
          description: |
            Filter transactions by class. Classes are hard coded and segment transaction into 8 broad categories:

            * `item` - an item the guest needs to pay for
            * `discount` - a discount the guest has received
            * `card-payment` - a credit card payment
            * `card-refund` - a credit card refund
            * `non-cc-payment` - a non credit card payment (cash, wire transfer, etc)
            * `non-cc-refund` - a non credit card refund
            * `person-credit` - personal credit was added for the guest
            * `person-debit` - personal credit was used for payment

        - name: program_id
          in: query
          type: integer
          description: |
            Filter transactions for a specific program.

        - name: registration_id
          in: query
          type: array
          items:
            type: integer
          description: |
            Filter transactions for a specific registration or registrations.

        - name: min_date
          in: query
          type: string
          format: date
          description: |
            Filter transactions that were submitted on or after this date.


        - name: max_date
          in: query
          type: string
          format: date
          description: |
            Filter transactions that were submitted on or before this date.

        - name: category
          in: query
          type: array
          items:
            type: string
          description: |
            Filter transactions by category. Categories are user defined and can be very specific.

      responses:
        200:
          description:
            An array of transactions
          schema:
            type: array
            items:
              $ref: '#/definitions/Transaction'
        400:
          description: An error
          schema:
            $ref: '#/definitions/Error'


definitions:

  Program:
    type: object
    description: A single program
    properties:
      id:
        type: integer
        description: internal unique id
      self_url:
        type: string
        format: url
        description: API URL pointing back to the object
      name:
        type: string
        description: program name
      start_date:
        type: string
        description: program start date
      end_date:
        type: string
        description: program end date
      registrations_url:
        type: string
        description: API URL for program registrations
      transactions_url:
        type: string
        description: API URL for program transactions
      teachers:
        type: array
        items:
          type: string
        description: teacher names for the program

  Registration:
    type: object
    description: A single registration by a guest to a program.
    properties:
      id:
        type: integer
        description: internal unique id
      self_url:
        type: string
        description: API URL pointing back to the object
        format: url
      submitted:
        type: string
        description: time the registration was submitted
        format: date-time
      start_date:
        type: string
        description: the day the guest's stay starts
        format: date
      end_date:
        type: string
        description: the day the guest's stay ends
        format: date
      status:
        type: string
        description: registration status [pending, reserved, cancelled, etc...]
      first_name:
        type: string
        description: guest's first name
      last_name:
        type: string
        description: guest's last name
      full_name:
        type: string
        description: guest's full name
      email:
        type: string
        format: email
        description: guest's email address
      program:
        type: string
        description: name of program the registration is for
      program_url:
        type: string
        format: url
        description: URL for API representation of program
      program_categories:
        type: array
        items:
          type: string
        description: categories for the program
      transactions_url:
        type: string
        format: url
        description: API URL for registration's transactions
      optional_items:
        type: array
        items:
          type: string
        description: optional items (add-ons) selected for the registration
      room:
        type: string
        description: name of room guest will be staying in
      lodging:
        type: string
        description: name of lodging type selected
      nights:
        type: integer
        description: total nights of stay
      grand_total:
        type: string
        format: decimal
        description: total amount owed for the registration
      balance_due:
        type: string
        format: decimal
        description: current balance
      guest_statement_link:
        type: string
        format: url
        description: link to the (user-facing) guest statement
      guest_edit_link:
        type: string
        format: url
        description: link to guest edit page (where a guest can update their details)
      questions:
        type: array
        description: an array of all the custom fields that have been configured for the program for which this registration was entered

  Transaction:
    type: object
    description: A single transaction
    properties:
      id:
        type: integer
        description: internal unique id

      self_url:
        type: string
        description: API URL pointing back to the object

      submitted:
        type: string
        format: date-time
        description: exact time when transaction was submitted

      trans_date:
        type: string
        format: date-time
        description: exact time of the transaction (can be modified manually, as opposed to `submitted`)

      program_id:
        type: string
        description: id of program for which this transaction was made

      program_name:
        type: string
        description: name of program for which this transaction was made

      program_url:
        type: string
        description: API URL of program for which this transaction was made

      class:
        type: string
        description: coarce grained classification of transactions

      category:
        type: string
        description: fine grained (and user defined) classification of transactions

      # description:
      #   type: string
      #   description:

      # status:
      #   type: string
      #   description:

      # notes:
      #   type: string
      #   description:

      # staff_name:
      #   type: string
      #   description:

      # charge_amount:
      #   type: string
      #   description:

      # credit_amount:
      #   type: string
      #   description:


      # person_id:
      #   type: string
      #   description:

      # person_name:
      #   type: string
      #   description:

      # registration_id:
      #   type: string
      #   description:

      # registration_url:
      #   type: string
      #   description:


      # discount_amount:
      #   type: string
      #   description:

      # discount_percent:
      #   type: string
      #   description:

      # subtotal:
      #   type: string
      #   description:

      # tax_1_info:
      #   type: string
      #   description:

      # tax_1_amount:
      #   type: string
      #   description:

      # tax_2_info:
      #   type: string
      #   description:

      # tax_2_amount:
      #   type: string
      #   description:

      # grand_total:
      #   type: string
      #   description:

      # is_addon:
      #   type: string
      #   description:


      # fund_method:
      #   type: string
      #   description:

      # merchant_name:
      #   type: string
      #   description:

      # merchant_trans_id:
      #   type: string
      #   description:

      # merchant_profile:
      #   type: string
      #   description:

      # merchant_account:
      #   type: string
      #   description:

      # merchant_cc_details:
      #   type: string
      #   description:


  Error:
    type: object
    description: An error returned in case of an incorrect request.
    properties:
      message:
        type: string
        description: description of error and steps to correct it
