swagger: '2.0'
info:
  title: Retreat Booking Guru API
  version: "1.0.0"
  description: |
    This is the API definition for Booking Guru, and online software package
    designed for retreat centers to manage bookings, retreats, rooms and
    finances. The API allows access to programs, registrations and transactions
    that are stored within the system to allow integration with custom software.
    The same API is also used in our Zapier integration that allows connecting
    Booking Guru to other applications without the need for custom code.

schemes: https
basePath: /api/v1
produces: application/json
  
paths:
  /registrations:
    get:
      summary: Registrations
      description: |
        Registration details including names, emails and programs people have registered to.
      parameters:
        - name: limit
          type: integer
          description: |
            Limit number of return values. The default limit is 20. Pass `limit=0` To get all the registrations without
            limits, but please use this with caution to not overload our servers.
      responses:
        200:
          description:
            An array of registrations.
          schema:
            type: array
            items:
              $ref: '#/definitions/Registration'
        default:
          description: Error
          schema:
            $ref: '#/definitions/Error'

definitions:
  Registration:
    type: object
    properties:
      id:
        type: integer
      first_name:
        type: string
      last_name:
        type: string
      start_date:
        type: string
        format: date
      end_date:
        type: string
        format: date
      submitted:
        type: string
        format: dateTime

  Error:
    type: object
    properties:
      message:
        type: string
